# title = "Peer iOS Frontend Gitleaks Config"

[[rules]]
id = "ios-catch-all"
description = "Catch likely secrets in iOS/Swift code (Firebase, API keys, JWT, Apple tokens, etc.)"
regex = '''(?i)(ghp_[0-9A-Za-z]{36}|github_pat_[0-9A-Za-z_]{20,}|glpat-[0-9A-Za-z\-_]{20}|AKIA[0-9A-Z]{16}|ASIA[0-9A-Z]{16}|AIza[0-9A-Za-z\-_]{35}|AAAA[A-Za-z0-9_-]{5,}:[A-Za-z0-9_-]{20,}|sk_live_[0-9a-zA-Z]{24}|pk_live_[0-9a-zA-Z]{24}|eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9._-]+\.[A-Za-z0-9._-]+|-----BEGIN( RSA| DSA| EC| OPENSSH)? PRIVATE KEY-----)'''
tags = ["key", "secret", "frontend", "ios"]

[rules.allowlist]
description = "Ignore placeholders, test constants, and safe variable patterns"
regexes = [
  '''(?i)secrets\.[A-Za-z0-9_]+''',
  '''(?i)vars\.[A-Za-z0-9_]+''',
  '''(?i)github\.[A-Za-z0-9_]+''',
  '''(?i)Author:\s*\$DISCORD_MENTION["']?$'''
]

[allowlist]
description = "Ignore known safe cases"
regexes = [
  '''Author:\s*\$DISCORD_MENTION["']?$'''
]

[pathDenylist]
description = "Exclude noisy generated/test files for iOS builds"
regexes = [
  '''^Pods/.*''',
  '''^DerivedData/.*''',
  '''^build/.*''',
  '''^\.git/.*''',
  '''^\.github/workflows/.*''',
  '''^fastlane/.*''',
  '''^Tests?/.*''',
  '''^\.env.*$'''
]
