//
//  Images.swift
//  DesignSystem
//
//  Created by Артем Васин on 27.01.25.
//

import SwiftUI

@frozen
public enum Images {
    public static let logoText = Image(.logoText)
    public static let onboarding1 = Image(.onboarding1)
}

@frozen
public enum Icons {
    public static let checkmarkCircle = Image(.iconCheckmarkCircle)
    public static let xCircle = Image(.iconXCircle)
    public static let x = Image(.iconX)
    public static let xBold = Image(.iconXBold)
    public static let eye = Image(.iconEye)
    public static let eyeSlash = Image(.iconEyeSlash)
    public static let bubble = Image(.iconBubble)
    public static let bubbleBold = Image(.iconBubbleBold)
    public static let bubbleFill = Image(.iconBubbleFill)
    public static let bubbleDots = Image(.iconBubbleDots)
    public static let ellipsis = Image(.iconEllipsis)
    public static let eyeCircled = Image(.iconEyeCircled)
    public static let eyeCircledFill = Image(.iconEyeCircledFill)
    public static let heart = Image(.iconHeart)
    public static let heartBold = Image(.iconHeartBold)
    public static let heartBroke = Image(.iconHeartBroke)
    public static let heartBrokeBold = Image(.iconHeartBrokeBold)
    public static let heartBrokeFill = Image(.iconHeartBrokeFill)
    public static let heartFill = Image(.iconHeartFill)
    public static let house = Image(.iconHouse)
    public static let houseFill = Image(.iconHouseFill)
    public static let magnifyingglass = Image(.iconMagnifyingglass)
    public static let magnifyingglassFill = Image(.iconMagnifyingglassFill)
    public static let person = Image(.iconPerson)
    public static let personFill = Image(.iconPersonFill)
    public static let playRectangle = Image(.iconPlayRectangle)
    public static let play = Image(.iconPlay)
    public static let pause = Image(.iconPause)
    public static let plustSquare = Image(.iconPlustSquare)
    public static let plustSquareFill = Image(.iconPlustSquareFill)
    public static let smile = Image(.iconSmile)
    public static let wallet = Image(.iconWallet)
    public static let walletFill = Image(.iconWalletFill)
    public static let plus = Image(.iconPlus)
    public static let plusBold = Image(.iconPlusBold)
    public static let arrowDown = Image(.iconArrowDown)
    public static let arrowDownNormal = Image(.iconNormalArrowDown)
    public static let arrowNormal = Image(.iconNormalArrow)
    public static let arrowsBackToBack = Image(.iconArrowsBackToBack)
    public static let arrowsBackRounded = Image(.iconArrowBackRounded)
    public static let musicNote = Image(.iconMusicNote)
    public static let arrowCounterClockwise = Image(.iconArrowCounterClockwise)
    public static let exclamationMarkTriangleBlack = Image(.iconExclamationMarkTriangleBlack)
    public static let exclamationMarkTriangleWhite = Image(.iconExclamationMarkTriangleWhite)
    public static let arrowBack = Image(.iconArrowBack)
    public static let block = Image(.iconBlock)
    public static let longArrowRight = Image(.iconLongArrowRight)
    public static let logoCircleWhite = Image(.iconLogoCircleWhite)
    public static let logoCircleBlue = Image(.iconLogoCircleBlue)
    public static let a = Image(.iconA)
    public static let folder = Image(.iconFolder)
    public static let folderMusic = Image(.iconFolderMusic)
    public static let musicBars = Image(.iconMusicBars)
    public static let pen = Image(.iconPen)
    public static let share = Image(.iconShare)
    public static let gear = Image(.iconGear)
    public static let trashBin = Image(.iconTrashBin)
    public static let checkmark = Image(.iconCheckmark)
    public static let doubleCheckmark = Image(.iconDoubleCheckmark)
    public static let gem = Image(.iconGem)
    public static let clock = Image(.iconClock)
    public static let graph = Image(.iconGraph)
    public static let camera = Image(.iconCamera)
    public static let bookmark = Image(.iconBookmark)
    public static let arrowShare = Image(.iconArrowShare)
    public static let shareVia = Image(.iconShareVia)
    public static let copy = Image(.iconCopy)
    public static let copyDone = Image(.iconCopyDone)
    public static let checkMarkSqareEnable = Image(.iconCheckmarkSquareEnable)
    public static let checkMarkSqareDisable = Image(.iconCheckmarkSquareDisable)
    public static let lock = Image(.iconLock)
    public static let ad = Image(.iconAd)
    public static let shop = Image(.iconShop)
    public static let btcExchange = Image(.iconBtcExchange)
    public static let pin = Image(.iconPin)
}

@frozen
public enum IconsNew {
    public static let ageRestriction = Image(.icAgeRestriction)
    public static let arrowRight = Image(.icArrowRight)
    public static let checkCircle = Image(.icCheckCircle)
    public static let checkCircle2 = Image(.icCheckCircle2)
    public static let copy = Image(.icCopy)
    public static let envelope = Image(.icEnvelope)
    public static let envelopeWithCode = Image(.icEnvelopeWithCode)
    public static let eye = Image(.icEye)
    public static let eyeWithSlash = Image(.icEyeWithSlash)
    public static let lock = Image(.icLock)
    public static let person = Image(.icPerson)
    public static let referral = Image(.icReferral)
    public static let megaphone = Image(.icMegaphone)
    public static let exclamaitionMarkCircle = Image(.icExclamationMarkCircle)
    public static let clockAndMoney = Image(.icClockAndMoney)
    public static let shop = Image(.icShop)
    public static let shopFill = Image(.icShopFill)
    public static let bubbleLines = Image(.icBubbleLines)
    public static let placeholder = Image(.icPlaceholder)
    public static let flag = Image(.icFlag)
    public static let houseLocation = Image(.icHouseLocation)
    public static let globe = Image(.icGlobe)
}
